### ISSUE TITLE
application-oauth.yaml 파일 관리

### ISSUE THREAD

**Issue by wisdom08** [wisdom08/dev-community#12]
## Description
- 헤로쿠로 배포했을 때는 데이터베이스 등의 민감 정보를 헤로쿠 사이트 내에 등록하는 방법을 사용했었다. 
- 그런데 헤로쿠를 이용하지 않고, 배포하기 전에는 application-oauth.yaml 파일의 민감 정보 관리를 어떻게 해야하는지 파악하고 적용해보자. 
- 현재는 application-oauth.yaml 파일이 깃이그노어에 등록되어 있고 다른 사람이 실행할 수 없는 상태이다.

**Comment by jongfeel** [comment]
Jasypt라는 게 있는데 한번 적용해 보시면 어떨까요?

https://stackoverflow.com/questions/37404703/spring-boot-how-to-hide-passwords-in-properties-file

**Comment by wisdom08** [comment]
저런 게 있군요 
처음 봅니다. 찾아보고 적용해보겠습니다!
