### ISSUE TITLE
추가 작업 계획

### ISSUE THREAD

**Issue by jongfeel** [wisdom08/dev-community#27]
- 작성자 관련해서는 bulma 는 임시값으로 글 작성 화면에만 들어가는 값이고 데이터베이스에는 저장되지 않는 값이어서 게시글 목록에는 보여지지 않고 있습니다. 게시글 목록에서 작성자값은 실제 작성자값이 들어갈 수 있도록 추가할 계획입니다. 
- 게시글 상세보기의 경우 아직 개발되지 않았습니다. 추가 개발해야하는 화면입니다. 
- 로그인 유지와 관련해서 고민한 내용은 JWT 방식이 쿠키, 세션의 단점을 보안해서 나온 것이라는 건 알겠는데 JWT 방식으로 하게된다면 프로젝트 규모에 적절한 방식이 맞는지 고민을 했고, 쿠키/세션/JWT 각각 개발 공수를 파악하기가 어려워서 고민을 했습니다.

_Originally posted by @wisdom08 in https://github.com/wisdom08/dev-community/issues/26#issuecomment-1263751433_

**Comment by jongfeel** [comment]
1번의 경우 작성자 id가 들어갈 수 있게 수정 진행하면 좋을 것 같습니다.

2번의 경우 추가 개발 계획을 잡고 진행해야 하는 부분 같습니다.
=> 이것과 관련하여 회고 내용으로 "계획한 내용"과 "실제 작업한 내용"의 일치성에 대해 얘기해 보려고 합니다.

3번의 경우 스터디를 더 진행해 보시면 좋을 것 같습니다. 우선 JWT가 좋은 방식인 건 파악 하셨으니 진행해 보면서 파악하는 것도 좋습니다.
로그인 유지와 관련된 구체적인 작전과 계획이 있으면 좋을 것 같습니다.

**Comment by wisdom08** [comment]
네 제 머릿속에만 있었거나 제가 생각하지 못했던 부분들을 구체적으로 잘 작성을 해보겠습니다. 
일치성의 문제도 아직 제대로 해낸 적이 없어서 자신이 없지만 조금씩 이뤄나가보겠습니다.

**Comment by wisdom08** [comment]
네 JWT 구현 방식에 대한 구체적인 계획을 정리해볼게요. 
감사합니다!
