### ISSUE TITLE
소셜 로그인

### ISSUE THREAD

**Issue by wisdom08** [wisdom08/dev-community#4]
## Description

> 소셜 로그인 기능과 화면을 구현합니다.

## Progress

- [x] OAuth2.0 개념 이해 및 동작 방식 파악 후 문서화
- [x] 카카오 로그인 서비스 구현
- [x] 깃허브 로그인 서비스 구현
- [x] 구글 로그인 서비스 구현
- [x] #8
- [x] 스프링부트-소셜로그인 연동
- [ ] 로그인이 일정시간 동안 유지되게 만들어야한다.

**Comment by wisdom08** [comment]
[참고: OAuth2.0 문서화](https://velog.io/@wisdom08/OAuth-2.0)

**Comment by wisdom08** [comment]
로그인이 유지될 수 있게 JWT 토큰을 적용한다.
- 먼저, 토큰을 발급하고 검증할 수 있는 컴포넌트를 작성하려고 한다.

**Comment by wisdom08** [comment]
컴포넌트 작성 전에 JWT 의존성 추가해야함

**Comment by wisdom08** [comment]
2022.10.10 작업 결과
- 토큰 프로바이더를 추가하려고 하니까`UserDetailsServiceImpl ` 객체를 필요로 하는데 해당 부분까지는 구현하지 못했다. 
- `UserDetailsServiceImpl`객체에 대해 찾아봐야 함

**Comment by jongfeel** [comment]
Iteration 3의 작업 계획 issue를 만들고
그 하위에 10월 10일 작업 결과를 적어 보는 게 좋을 것 같습니다.
